services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: tourplanner
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tourplanner
    ports:
      - "5432:5432"

  server:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tourplanner
      SPRING_DATASOURCE_USERNAME: tourplanner
      SPRING_DATASOURCE_PASSWORD: password
    volumes:
      - ./files:/app/files